version: '3.9'

networks:
  network:
    driver: ${NETWORKS_DRIVER?}

volumes:
  mysql:
    name: ${COMPOSE_PROJECT_NAME?}_mysql-${ENV?}
    driver: ${VOLUMES_DRIVER?}
  mysql_test:
    name: ${COMPOSE_PROJECT_NAME?}_mysql_test-${ENV?}
    driver: ${VOLUMES_DRIVER?}
  redis:
    name: ${COMPOSE_PROJECT_NAME?}_redis-${ENV?}
    driver: ${VOLUMES_DRIVER?}

services:
  php-fpm:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  php-worker:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${NGINX_HOST_HTTP_PORT:-8080}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      network:
        aliases:
          - ${APP_HOST?}
#    depends_on:
#      - php-fpm

  application:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/application-${ENV?}:${TAG?}
    container_name: ${COMPOSE_PROJECT_NAME?}_application-${ENV?}
    build:
      context: ../
      dockerfile: ./images/php/application/Dockerfile
      args:
        - BASE_IMAGE=${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/php-base-${ENV?}:${TAG?}
        - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
        - ENV=${ENV?}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    # cap_add and security_opt are required to enable strace
    # @see https://stackoverflow.com/a/46676868
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
    tty: true
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:${MYSQL_VERSION?}
    container_name: ${COMPOSE_PROJECT_NAME?}_mysql-${ENV?}
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-application_db}
      - MYSQL_USER=${MYSQL_USER:-application_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - network
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"

  mysql_test:
    image: mysql:${MYSQL_VERSION?}
    container_name: ${COMPOSE_PROJECT_NAME?}_mysql_test-${ENV?}
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-application_db_test}
      - MYSQL_USER=${MYSQL_USER:-application_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - mysql_test:/var/lib/mysql
    networks:
      - network
    ports:
      - "${MYSQL_HOST_PORT_TEST:-3306}:3306"

  redis:
    image: redis:${REDIS_VERSION?}
    container_name: ${COMPOSE_PROJECT_NAME?}_redis-${ENV?}
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    # @see https://stackoverflow.com/a/69498392/413531
    command: >
      --requirepass ${REDIS_PASSWORD?}
    volumes:
      - redis:/data
    networks:
      - network
